/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        primary: {
          100: '#e7f6ee',
          200: '#dbf2e5',
          300: '#b5e4c9',
          400: '#11a950',
          500: '#0f9848',
          600: '#0e8740',
          700: '#0d7f3c',
          800: '#0a6530',
          900: '#084c24',
          950: '#063b1c',
        },
        secondary: {
          100: '#eaf0f8',
          200: '#e0e8f4',
          300: '#bfd0e8',
          400: '#2f67b4',
          500: '#2a5da2',
          600: '#265290',
          700: '#234d87',
          800: '#1c3e6c',
          900: '#152e51',
          950: '#10243f',
        },
      },
    },
    fontFamily: {
      body: [
        'Inter',
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
        'system-ui',
        'Segoe UI',
        'Roboto',
        'Helvetica Neue',
        'Arial',
        'Noto Sans',
        'sans-serif',
        'Apple Color Emoji',
        'Segoe UI Emoji',
        'Segoe UI Symbol',
        'Noto Color Emoji',
      ],
      sans: [
        'Inter',
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
        'system-ui',
        'Segoe UI',
        'Roboto',
        'Helvetica Neue',
        'Arial',
        'Noto Sans',
        'sans-serif',
        'Apple Color Emoji',
        'Segoe UI Emoji',
        'Segoe UI Symbol',
        'Noto Color Emoji',
      ],
    },
  },
  plugins: [],
};
